Remove unneeded inline specifier
The function is not in an header file, and regular overloading is enough here.

On my machine it caused linking errors instead:

    ld: /build/ccadO8sz.o: in function `expr(char const*)':
    lex.yy.cpp:(.text+0x1bf9): undefined reference to `subst[abi:cxx11](char const*)'

This change should not affect the optimization of the same name.